const KEBAB = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

/** A token is emitted to a target when it declares no `targets` (all four) or lists it. */
export function allowsTarget(node, target) {
  return !node || !Array.isArray(node.targets) || node.targets.includes(target);
}

function colorVars(color, theme) {
  return Object.entries(color)
    .filter(([, v]) => allowsTarget(v, 'css'))
    .map(([k, v]) => `  --color-${KEBAB(k)}: ${v[theme]};`);
}

function callVars(call, theme) {
  const out = [];
  call.fill[theme].forEach((hex, i) => out.push(`  --call-fill-${i + 1}: ${hex};`));
  out.push(`  --call-ink: ${call.ink[theme]};`);
  out.push(`  --call-edge: ${call.edge[theme]};`);
  out.push(`  --call-slab: ${call.slab[theme]};`);
  for (const [surface, widths] of Object.entries(call.edgeWidth)) {
    widths.forEach((w, i) => out.push(`  --call-edge-w-${KEBAB(surface)}-${i + 1}: ${w}px;`));
  }
  return out;
}

/** Theme-invariant tokens: emitted once, in :root only. */
function staticVars(t) {
  const out = [];
  for (const [group, scale] of Object.entries({ space: t.space, gutter: t.gutter, control: t.control, border: t.border, radius: t.radius, size: t.size })) {
    for (const [k, v] of Object.entries(scale)) {
      if (Array.isArray(v) || typeof v === 'object') continue; // radius.bands, rail sub-objects
      out.push(`  --${group}-${KEBAB(k)}: ${typeof v === 'number' ? v + 'px' : v};`);
    }
  }
  for (const [k, v] of Object.entries(t.rail)) {
    if (typeof v === 'object') {
      for (const [dim, n] of Object.entries(v)) out.push(`  --rail-${KEBAB(k)}-${dim}: ${n}px;`);
    } else {
      out.push(`  --rail-${KEBAB(k)}: ${v};`);
    }
  }
  for (const [scope, styles] of Object.entries(t.type)) {
    for (const [name, s] of Object.entries(styles)) {
      if (!allowsTarget(s, 'css') || !allowsTarget(styles, 'css')) continue;
      if (name === 'targets' || name === 'unit') continue;
      const p = `--type-${KEBAB(scope)}-${KEBAB(name)}`;
      if (Array.isArray(s.size)) s.size.forEach((n, i) => out.push(`  ${p}-size-${i + 1}: ${n}px;`));
      else if (Array.isArray(s.clamp)) out.push(`  ${p}-size: clamp(${s.clamp[0]}px, ${s.clamp[1]}, ${s.clamp[2]}px);`);
      else if (s.size != null) out.push(`  ${p}-size: ${s.size}px;`);
      if (s.lineHeight != null) out.push(`  ${p}-lh: ${s.lineHeight > 3 ? s.lineHeight + 'px' : s.lineHeight};`);
      if (s.weight != null) out.push(`  ${p}-weight: ${s.weight};`);
      if (s.tracking) out.push(`  ${p}-tracking: ${s.tracking}em;`);
    }
  }
  out.push(`  --font-sans: ${t.font.sans.stack.map((f) => (f.includes(' ') ? `"${f}"` : f)).join(', ')};`);
  out.push(`  --font-mono: ${t.font.mono.stack.map((f) => (f.includes(' ') ? `"${f}"` : f)).join(', ')};`);
  out.push(`  --motion-fast: ${t.motion.fast}ms;`);
  out.push(`  --motion-base: ${t.motion.base}ms;`);
  out.push(`  --motion-ease: ${t.motion.ease};`);
  return out;
}

function themeBlock(t, theme) {
  return [...colorVars(t.color, theme), ...callVars(t.call, theme), `  --shadow-pop: ${t.shadow.pop[theme]};`];
}

export function emitCss(t) {
  const header = `/* GENERATED by tools/generate-tokens.mjs from tokens.json v${t.meta.version}. DO NOT EDIT. */\n`;
  const light = [...themeBlock(t, 'light'), ...staticVars(t), '  color-scheme: light;'];
  const dark = [...themeBlock(t, 'dark'), '  color-scheme: dark;'];
  return (
    header +
    `\n:root {\n${light.join('\n')}\n}\n` +
    `\n@media (prefers-color-scheme: dark) {\n  :root:not([data-theme="light"]) {\n${dark.map((l) => '  ' + l).join('\n')}\n  }\n}\n` +
    `\n:root[data-theme="dark"] {\n${dark.join('\n')}\n}\n`
  );
}

export function emitLanding(t, prevHtml) {
  const css = emitCss(t);
  const block = `/* @tokens:start */\n${css}/* @tokens:end */`;
  if (!prevHtml) return block;
  if (prevHtml.includes('/* @tokens:start */') && prevHtml.includes('/* @tokens:end */')) {
    return prevHtml.replace(/\/\* @tokens:start \*\/[\s\S]*?\/\* @tokens:end \*\//, block);
  }
  return prevHtml.replace(/\/\* ================= THEME TOKENS[\s\S]*?:root\[data-theme="dark"\]\s*\{[\s\S]*?color-scheme:\s*dark;\s*\}/, block);
}

export function emitTs(t) {
  const header = `/* GENERATED by tools/generate-tokens.mjs from tokens.json v${t.meta.version}. DO NOT EDIT. */\n\n`;
  const lightColor = {};
  const darkColor = {};
  for (const [k, v] of Object.entries(t.color)) {
    if (allowsTarget(v, 'ts')) {
      lightColor[k] = v.light;
      darkColor[k] = v.dark;
    }
  }

  const content = `export const tokens = {
  meta: { version: ${t.meta.version} },
  color: {
    light: ${JSON.stringify(lightColor, null, 4)},
    dark: ${JSON.stringify(darkColor, null, 4)},
  },
  call: {
    fill: {
      light: ${JSON.stringify(t.call.fill.light)},
      dark: ${JSON.stringify(t.call.fill.dark)},
    },
    ink: {
      light: ${JSON.stringify(t.call.ink.light)},
      dark: ${JSON.stringify(t.call.ink.dark)},
    },
    edge: {
      light: ${JSON.stringify(t.call.edge.light)},
      dark: ${JSON.stringify(t.call.edge.dark)},
    },
    slab: {
      light: ${JSON.stringify(t.call.slab.light)},
      dark: ${JSON.stringify(t.call.slab.dark)},
    },
    thresholdsSec: ${JSON.stringify(t.call.thresholdsSec)},
  },
  gutter: ${JSON.stringify(t.gutter, null, 4)},
  space: ${JSON.stringify(t.space, null, 4)},
  radius: ${JSON.stringify(t.radius, null, 4)},
  control: ${JSON.stringify(t.control, null, 4)},
} as const;

export type ThemeColors = typeof tokens.color.light;
export const lightColors: ThemeColors = tokens.color.light;
export const darkColors: ThemeColors = tokens.color.dark;
`;
  return header + content;
}

function hexToKotlinColor(hex) {
  let h = hex.replace('#', '');
  if (h.length === 6) h = 'FF' + h;
  return `Color(0x${h.toUpperCase()}L)`;
}

export function emitKotlin(t) {
  return `/* GENERATED by tools/generate-tokens.mjs from tokens.json v${t.meta.version}. DO NOT EDIT. */
package uz.soat.reminder

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

object NurseCallTokens {
    const val VERSION = ${t.meta.version}

    object ColorLight {
${Object.entries(t.color)
  .filter(([, v]) => allowsTarget(v, 'kotlin'))
  .map(([k, v]) => `        val ${k} = ${hexToKotlinColor(v.light)}`)
  .join('\n')}
    }

    object ColorDark {
${Object.entries(t.color)
  .filter(([, v]) => allowsTarget(v, 'kotlin'))
  .map(([k, v]) => `        val ${k} = ${hexToKotlinColor(v.dark)}`)
  .join('\n')}
    }

    object Call {
        val fillsLight = listOf(
${t.call.fill.light.map((h) => '            ' + hexToKotlinColor(h)).join(',\n')}
        )
        val fillsDark = listOf(
${t.call.fill.dark.map((h) => '            ' + hexToKotlinColor(h)).join(',\n')}
        )
        val inkLight = ${hexToKotlinColor(t.call.ink.light)}
        val inkDark = ${hexToKotlinColor(t.call.ink.dark)}
        val slabLight = ${hexToKotlinColor(t.call.slab.light)}
        val slabDark = ${hexToKotlinColor(t.call.slab.dark)}
        val thresholdsSec = listOf(${t.call.thresholdsSec.join(', ')})
    }

    object Size {
        val watchCallAckHeight = ${t.control['48']}L.dp
        val watchCallRoomNumberMax = ${t.type.watch.room.size[2]}L.sp
    }
}
`;
}
