const KEBAB = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

/** A token is emitted to a target when it declares no `targets` (all four) or lists it. */
export function allowsTarget(node, target) {
  return !node || !Array.isArray(node.targets) || node.targets.includes(target);
}

function colorVars(color, theme) {
  return Object.entries(color)
    .filter(([, v]) => allowsTarget(v, 'css'))
    .map(([k, v]) => `  --color-${KEBAB(k)}: ${v[theme]};`);
}

function callVars(call, theme) {
  const out = [];
  call.fill[theme].forEach((hex, i) => out.push(`  --call-fill-${i + 1}: ${hex};`));
  out.push(`  --call-ink: ${call.ink[theme]};`);
  out.push(`  --call-edge: ${call.edge[theme]};`);
  out.push(`  --call-slab: ${call.slab[theme]};`);
  for (const [surface, widths] of Object.entries(call.edgeWidth)) {
    widths.forEach((w, i) => out.push(`  --call-edge-w-${KEBAB(surface)}-${i + 1}: ${w}px;`));
  }
  return out;
}

/** Theme-invariant tokens: emitted once, in :root only. */
function staticVars(t) {
  const out = [];
  for (const [group, scale] of Object.entries({ space: t.space, gutter: t.gutter, control: t.control, border: t.border, radius: t.radius, size: t.size })) {
    for (const [k, v] of Object.entries(scale)) {
      if (Array.isArray(v) || typeof v === 'object') continue; // radius.bands, rail sub-objects
      out.push(`  --${group}-${KEBAB(k)}: ${typeof v === 'number' ? v + 'px' : v};`);
    }
  }
  for (const [k, v] of Object.entries(t.rail)) {
    if (typeof v === 'object') {
      for (const [dim, n] of Object.entries(v)) out.push(`  --rail-${KEBAB(k)}-${dim}: ${n}px;`);
    } else {
      out.push(`  --rail-${KEBAB(k)}: ${v};`);
    }
  }
  for (const [scope, styles] of Object.entries(t.type)) {
    for (const [name, s] of Object.entries(styles)) {
      if (!allowsTarget(s, 'css') || !allowsTarget(styles, 'css')) continue;
      if (name === 'targets' || name === 'unit') continue;
      const p = `--type-${KEBAB(scope)}-${KEBAB(name)}`;
      if (Array.isArray(s.size)) s.size.forEach((n, i) => out.push(`  ${p}-size-${i + 1}: ${n}px;`));
      else if (Array.isArray(s.clamp)) out.push(`  ${p}-size: clamp(${s.clamp[0]}px, ${s.clamp[1]}, ${s.clamp[2]}px);`);
      else if (s.size != null) out.push(`  ${p}-size: ${s.size}px;`);
      if (s.lineHeight != null) out.push(`  ${p}-lh: ${s.lineHeight > 3 ? s.lineHeight + 'px' : s.lineHeight};`);
      if (s.weight != null) out.push(`  ${p}-weight: ${s.weight};`);
      if (s.tracking) out.push(`  ${p}-tracking: ${s.tracking}em;`);
    }
  }
  out.push(`  --font-sans: ${t.font.sans.stack.map((f) => (f.includes(' ') ? `"${f}"` : f)).join(', ')};`);
  out.push(`  --font-mono: ${t.font.mono.stack.map((f) => (f.includes(' ') ? `"${f}"` : f)).join(', ')};`);
  out.push(`  --motion-fast: ${t.motion.fast}ms;`);
  out.push(`  --motion-base: ${t.motion.base}ms;`);
  out.push(`  --motion-ease: ${t.motion.ease};`);
  return out;
}

function themeBlock(t, theme) {
  return [...colorVars(t.color, theme), ...callVars(t.call, theme), `  --shadow-pop: ${t.shadow.pop[theme]};`];
}

export function emitCss(t) {
  const header = `/* GENERATED by tools/generate-tokens.mjs from tokens.json v${t.meta.version}. DO NOT EDIT. */\n`;
  const light = [...themeBlock(t, 'light'), ...staticVars(t), '  color-scheme: light;'];
  const dark = [...themeBlock(t, 'dark'), '  color-scheme: dark;'];
  return (
    header +
    `\n:root {\n${light.join('\n')}\n}\n` +
    `\n@media (prefers-color-scheme: dark) {\n  :root:not([data-theme="light"]) {\n${dark.map((l) => '  ' + l).join('\n')}\n  }\n}\n` +
    `\n:root[data-theme="dark"] {\n${dark.join('\n')}\n}\n`
  );
}

export function emitLanding(t, prevHtml) {
  const css = emitCss(t);
  const block = `/* @tokens:start */\n${css}/* @tokens:end */`;
  if (!prevHtml) return block;
  if (prevHtml.includes('/* @tokens:start */') && prevHtml.includes('/* @tokens:end */')) {
    return prevHtml.replace(/\/\* @tokens:start \*\/[\s\S]*?\/\* @tokens:end \*\//, block);
  }
  return prevHtml.replace(/\/\* ================= THEME TOKENS[\s\S]*?:root\[data-theme="dark"\]\s*\{[\s\S]*?color-scheme:\s*dark;\s*\}/, block);
}

/**
 * The dashboard's shared behavioural constants.
 *
 * This used to emit the Expo app's theme file -- an app that no longer exists,
 * so one of the generator's four outputs was being written into a dead
 * directory. It now emits the one thing the dashboard needs from the source
 * rather than from a hand copy: the urgency thresholds. ageStep.ts kept its own,
 * under a comment claiming "--check catches a divergence" -- which it did not,
 * as the phone proved by diverging unnoticed for weeks.
 *
 * Deliberately narrow. Colours reach the dashboard as CSS custom properties;
 * only values TypeScript has to branch on belong here.
 */
export function emitTs(t) {
  return `// GENERATED by tools/generate-tokens.mjs from tokens.json v${t.meta.version}. DO NOT EDIT.

/** Seconds at which a waiting call moves to the next urgency step. */
export const THRESHOLDS_SEC = [${t.call.thresholdsSec.join(', ')}] as const;

export const TOKENS_VERSION = ${t.meta.version};
`;
}

function hexToKotlinColor(hex) {
  let h = hex.replace('#', '');
  if (h.length === 6) h = 'FF' + h;
  return `Color(0x${h.toUpperCase()}L)`;
}

export function emitKotlin(t) {
  return `/* GENERATED by tools/generate-tokens.mjs from tokens.json v${t.meta.version}. DO NOT EDIT. */
package uz.soat.reminder

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

object NurseCallTokens {
    const val VERSION = ${t.meta.version}

    object ColorLight {
${Object.entries(t.color)
  .filter(([, v]) => allowsTarget(v, 'kotlin'))
  .map(([k, v]) => `        val ${k} = ${hexToKotlinColor(v.light)}`)
  .join('\n')}
    }

    object ColorDark {
${Object.entries(t.color)
  .filter(([, v]) => allowsTarget(v, 'kotlin'))
  .map(([k, v]) => `        val ${k} = ${hexToKotlinColor(v.dark)}`)
  .join('\n')}
    }

    object Call {
        val fillsLight = listOf(
${t.call.fill.light.map((h) => '            ' + hexToKotlinColor(h)).join(',\n')}
        )
        val fillsDark = listOf(
${t.call.fill.dark.map((h) => '            ' + hexToKotlinColor(h)).join(',\n')}
        )
        val inkLight = ${hexToKotlinColor(t.call.ink.light)}
        val inkDark = ${hexToKotlinColor(t.call.ink.dark)}
        val slabLight = ${hexToKotlinColor(t.call.slab.light)}
        val slabDark = ${hexToKotlinColor(t.call.slab.dark)}
        val thresholdsSec = listOf(${t.call.thresholdsSec.join(', ')})
    }

    object Size {
        val watchCallAckHeight = ${t.control['48']}.dp
        val watchCallRoomNumberMax = ${t.type.watch.room.size[2]}.sp
    }
}
`;
}

/**
 * The Flutter nurse app.
 *
 * Added after a review found the phone was the one surface NOT generated from
 * tokens.json -- and that it had already drifted, in the way that matters most.
 * The watch and the dashboard escalated a call's colour at one pair of
 * thresholds; the phone, which copied the numbers by hand, used another. The
 * same patient's call therefore sat amber on the ward watch while the nurse's
 * own phone still showed it calm.
 *
 * Only facts that must be IDENTICAL across surfaces are emitted. The phone's
 * palette is deliberately its own -- it follows the approved Stitch design,
 * which is a different blue from the dashboard's -- and stays hand-written in
 * theme/tokens.dart. A design choice per surface is not the same kind of thing
 * as a shared fact about when a call counts as urgent.
 */
export function emitDart(t) {
  return `// GENERATED by tools/generate-tokens.mjs from tokens.json v${t.meta.version}. DO NOT EDIT.
//
// Only cross-surface facts live here: values where the phone disagreeing with
// the ward watch would mean two people looking at the same patient and seeing
// different urgency. The phone's own palette is in theme/tokens.dart.

/// Seconds at which a waiting call moves to the next urgency step.
const List<int> kCallThresholdsSec = [${t.call.thresholdsSec.join(', ')}];

/// The tokens.json version these came from, so a mismatch is traceable.
const int kTokensVersion = ${t.meta.version};
`;
}
