const KEBAB = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

/** A token is emitted to a target when it declares no `targets` (all four) or lists it. */
export function allowsTarget(node, target) {
  return !node || !Array.isArray(node.targets) || node.targets.includes(target);
}

function colorVars(color, theme) {
  return Object.entries(color)
    .filter(([, v]) => allowsTarget(v, 'css'))
    .map(([k, v]) => `  --color-${KEBAB(k)}: ${v[theme]};`);
}

function callVars(call, theme) {
  const out = [];
  call.fill[theme].forEach((hex, i) => out.push(`  --call-fill-${i + 1}: ${hex};`));
  out.push(`  --call-ink: ${call.ink[theme]};`);
  out.push(`  --call-edge: ${call.edge[theme]};`);
  out.push(`  --call-slab: ${call.slab[theme]};`);
  for (const [surface, widths] of Object.entries(call.edgeWidth)) {
    widths.forEach((w, i) => out.push(`  --call-edge-w-${KEBAB(surface)}-${i + 1}: ${w}px;`));
  }
  return out;
}

/** Theme-invariant tokens: emitted once, in :root only. */
function staticVars(t) {
  const out = [];
  for (const [group, scale] of Object.entries({ space: t.space, gutter: t.gutter, control: t.control, border: t.border, radius: t.radius, size: t.size })) {
    for (const [k, v] of Object.entries(scale)) {
      if (Array.isArray(v) || typeof v === 'object') continue; // radius.bands, rail sub-objects
      out.push(`  --${group}-${KEBAB(k)}: ${typeof v === 'number' ? v + 'px' : v};`);
    }
  }
  for (const [k, v] of Object.entries(t.rail)) {
    if (typeof v === 'object') {
      for (const [dim, n] of Object.entries(v)) out.push(`  --rail-${KEBAB(k)}-${dim}: ${n}px;`);
    } else {
      out.push(`  --rail-${KEBAB(k)}: ${v};`);
    }
  }
  for (const [scope, styles] of Object.entries(t.type)) {
    for (const [name, s] of Object.entries(styles)) {
      if (!allowsTarget(s, 'css') || !allowsTarget(styles, 'css')) continue;
      if (name === 'targets' || name === 'unit') continue;
      const p = `--type-${KEBAB(scope)}-${KEBAB(name)}`;
      if (Array.isArray(s.size)) s.size.forEach((n, i) => out.push(`  ${p}-size-${i + 1}: ${n}px;`));
      else if (Array.isArray(s.clamp)) out.push(`  ${p}-size: clamp(${s.clamp[0]}px, ${s.clamp[1]}, ${s.clamp[2]}px);`);
      else if (s.size != null) out.push(`  ${p}-size: ${s.size}px;`);
      if (s.lineHeight != null) out.push(`  ${p}-lh: ${s.lineHeight > 3 ? s.lineHeight + 'px' : s.lineHeight};`);
      if (s.weight != null) out.push(`  ${p}-weight: ${s.weight};`);
      if (s.tracking) out.push(`  ${p}-tracking: ${s.tracking}em;`);
    }
  }
  out.push(`  --font-sans: ${t.font.sans.stack.map((f) => (f.includes(' ') ? `"${f}"` : f)).join(', ')};`);
  out.push(`  --font-mono: ${t.font.mono.stack.map((f) => (f.includes(' ') ? `"${f}"` : f)).join(', ')};`);
  out.push(`  --motion-fast: ${t.motion.fast}ms;`);
  out.push(`  --motion-base: ${t.motion.base}ms;`);
  out.push(`  --motion-ease: ${t.motion.ease};`);
  return out;
}

function themeBlock(t, theme) {
  return [...colorVars(t.color, theme), ...callVars(t.call, theme), `  --shadow-pop: ${t.shadow.pop[theme]};`];
}

export function emitCss(t) {
  const header = `/* GENERATED by tools/generate-tokens.mjs from tokens.json v${t.meta.version}. DO NOT EDIT. */\n`;
  const light = [...themeBlock(t, 'light'), ...staticVars(t), '  color-scheme: light;'];
  const dark = [...themeBlock(t, 'dark'), '  color-scheme: dark;'];
  return (
    header +
    `\n:root {\n${light.join('\n')}\n}\n` +
    `\n@media (prefers-color-scheme: dark) {\n  :root:not([data-theme="light"]) {\n${dark.map((l) => '  ' + l).join('\n')}\n  }\n}\n` +
    `\n:root[data-theme="dark"] {\n${dark.join('\n')}\n}\n`
  );
}
