// GENERATED by tools/generate-tokens.mjs from tokens.json v1. DO NOT EDIT.

/** Seconds at which a waiting call moves to the next urgency step. */
export const THRESHOLDS_SEC = [0, 120, 600] as const;

export const TOKENS_VERSION = 1;
