/* GENERATED by tools/generate-tokens.mjs from tokens.json v1. DO NOT EDIT. */
package uz.soat.reminder

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

object NurseCallTokens {
    const val VERSION = 1

    object ColorLight {
        val bg = Color(0xFFF8FAFCL)
        val surface = Color(0xFFFFFFFFL)
        val surfaceSoft = Color(0xFFF1F5F9L)
        val surfaceSunken = Color(0xFFE2E8F0L)
        val border = Color(0xFFE2E8F0L)
        val borderStrong = Color(0xFFCBD5E1L)
        val borderField = Color(0xFF64748BL)
        val text1 = Color(0xFF0F172AL)
        val text2 = Color(0xFF334155L)
        val text3 = Color(0xFF64748BL)
        val textDisabled = Color(0xFF94A3B8L)
        val accent = Color(0xFF0284C7L)
        val accentHover = Color(0xFF0369A1L)
        val accentPress = Color(0xFF075985L)
        val accentInk = Color(0xFFFFFFFFL)
        val accentSoft = Color(0x0284C71FL)
        val attn = Color(0xFFD97706L)
        val attnSoft = Color(0xF59E0B1FL)
        val ok = Color(0xFF10B981L)
    }

    object ColorDark {
        val bg = Color(0xFF0F172AL)
        val surface = Color(0xFF1E293BL)
        val surfaceSoft = Color(0xFF334155L)
        val surfaceSunken = Color(0xFF0F172AL)
        val border = Color(0xFF334155L)
        val borderStrong = Color(0xFF475569L)
        val borderField = Color(0xFF94A3B8L)
        val text1 = Color(0xFFF8FAFCL)
        val text2 = Color(0xFFCBD5E1L)
        val text3 = Color(0xFF94A3B8L)
        val textDisabled = Color(0xFF64748BL)
        val accent = Color(0xFF38BDF8L)
        val accentHover = Color(0xFF0284C7L)
        val accentPress = Color(0xFF0369A1L)
        val accentInk = Color(0xFF0F172AL)
        val accentSoft = Color(0x38BDF82EL)
        val attn = Color(0xFFF59E0BL)
        val attnSoft = Color(0xF59E0B2EL)
        val ok = Color(0xFF34D399L)
    }

    object Call {
        val fillsLight = listOf(
            Color(0xFFC4241AL),
            Color(0xFFA81810L),
            Color(0xFF8A100AL)
        )
        val fillsDark = listOf(
            Color(0xFFC02619L),
            Color(0xFFCF3224L),
            Color(0xFFDA3A2CL)
        )
        val inkLight = Color(0xFFFFFFFFL)
        val inkDark = Color(0xFFFFFFFFL)
        val slabLight = Color(0xFFFFFFFFL)
        val slabDark = Color(0xFFFFFFFFL)
        val thresholdsSec = listOf(0, 30, 120)
    }

    object Size {
        val watchCallAckHeight = 48.dp
        val watchCallRoomNumberMax = 48.sp
    }
}
