/* GENERATED by tools/generate-tokens.mjs from tokens.json v1. DO NOT EDIT. */
package uz.soat.reminder

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

object NurseCallTokens {
    const val VERSION = 1

    object ColorLight {
        val bg = Color(0xFFF6F7F7L)
        val surface = Color(0xFFFFFFFFL)
        val surfaceSoft = Color(0xFFFAFBFBL)
        val surfaceSunken = Color(0xFFEEF0F0L)
        val border = Color(0xFFE2E5E5L)
        val borderStrong = Color(0xFFC7CCCCL)
        val borderField = Color(0xFF8B9293L)
        val text1 = Color(0xFF14191AL)
        val text2 = Color(0xFF4A5456L)
        val text3 = Color(0xFF6C7679L)
        val textDisabled = Color(0xFFA2A9A9L)
        val accent = Color(0xFF0C6A62L)
        val accentHover = Color(0xFF0A5A54L)
        val accentPress = Color(0xFF095049L)
        val accentInk = Color(0xFFFFFFFFL)
        val accentSoft = Color(0x0C6A621FL)
        val attn = Color(0xFF8A5A00L)
        val attnSoft = Color(0x8A5A0016L)
        val ok = Color(0xFF146B3AL)
    }

    object ColorDark {
        val bg = Color(0xFF0E1213L)
        val surface = Color(0xFF171C1DL)
        val surfaceSoft = Color(0xFF131819L)
        val surfaceSunken = Color(0xFF0A0E0FL)
        val border = Color(0xFF272E2FL)
        val borderStrong = Color(0xFF394142L)
        val borderField = Color(0xFF697374L)
        val text1 = Color(0xFFE9EDEDL)
        val text2 = Color(0xFFA4AEAEL)
        val text3 = Color(0xFF7B8586L)
        val textDisabled = Color(0xFF4E5758L)
        val accent = Color(0xFF35C9B6L)
        val accentHover = Color(0xFF4FD6C4L)
        val accentPress = Color(0xFF63DFCEL)
        val accentInk = Color(0xFF04120FL)
        val accentSoft = Color(0x35C9B62EL)
        val attn = Color(0xFFE0A63AL)
        val attnSoft = Color(0xE0A63A24L)
        val ok = Color(0xFF3FC97EL)
    }

    object Call {
        val fillsLight = listOf(
            Color(0xFFC4241AL),
            Color(0xFFA81810L),
            Color(0xFF8A100AL)
        )
        val fillsDark = listOf(
            Color(0xFFB9271BL),
            Color(0xFFCB2F22L),
            Color(0xFFD93726L)
        )
        val inkLight = Color(0xFFFFFFFFL)
        val inkDark = Color(0xFFFFFFFFL)
        val slabLight = Color(0xFFFFFFFFL)
        val slabDark = Color(0xFFFFFFFFL)
        val thresholdsSec = listOf(0, 30, 120)
    }

    object Size {
        val watchCallAckHeight = 48L.dp
        val watchCallRoomNumberMax = 48L.sp
    }
}
