/* GENERATED by tools/generate-tokens.mjs from tokens.json v1. DO NOT EDIT. */

export const tokens = {
  meta: { version: 1 },
  color: {
    light: {
    "bg": "#F8FAFC",
    "surface": "#FFFFFF",
    "surfaceSoft": "#F1F5F9",
    "surfaceSunken": "#E2E8F0",
    "border": "#E2E8F0",
    "borderStrong": "#CBD5E1",
    "borderField": "#64748B",
    "text1": "#0F172A",
    "text2": "#334155",
    "text3": "#64748B",
    "textDisabled": "#94A3B8",
    "accent": "#0284C7",
    "accentHover": "#0369A1",
    "accentPress": "#075985",
    "accentInk": "#FFFFFF",
    "accentSoft": "#0284C71F",
    "attn": "#D97706",
    "attnSoft": "#F59E0B1F",
    "ok": "#10B981"
},
    dark: {
    "bg": "#0F172A",
    "surface": "#1E293B",
    "surfaceSoft": "#334155",
    "surfaceSunken": "#0F172A",
    "border": "#334155",
    "borderStrong": "#475569",
    "borderField": "#94A3B8",
    "text1": "#F8FAFC",
    "text2": "#CBD5E1",
    "text3": "#94A3B8",
    "textDisabled": "#64748B",
    "accent": "#38BDF8",
    "accentHover": "#0284C7",
    "accentPress": "#0369A1",
    "accentInk": "#0F172A",
    "accentSoft": "#38BDF82E",
    "attn": "#F59E0B",
    "attnSoft": "#F59E0B2E",
    "ok": "#34D399"
},
  },
  call: {
    fill: {
      light: ["#C4241A","#A81810","#8A100A"],
      dark: ["#C02619","#CF3224","#DA3A2C"],
    },
    ink: {
      light: "#FFFFFF",
      dark: "#FFFFFF",
    },
    edge: {
      light: "#6E0A06",
      dark: "#FF6B54",
    },
    slab: {
      light: "#FFFFFF",
      dark: "#FFFFFF",
    },
    thresholdsSec: [0,30,120],
  },
  gutter: {
    "app": 24,
    "appNarrow": 16,
    "phone": 16,
    "wall": 32,
    "landing": 24,
    "watch": 10
},
  space: {
    "0": 0,
    "2": 2,
    "4": 4,
    "8": 8,
    "12": 12,
    "16": 16,
    "20": 20,
    "24": 24,
    "32": 32,
    "40": 40,
    "48": 48,
    "64": 64,
    "80": 80,
    "112": 112
},
  radius: {
    "0": 0,
    "1": 4,
    "2": 8,
    "3": 12,
    "4": 16,
    "full": 999,
    "bands": [
        [
            0,
            32,
            1
        ],
        [
            32,
            64,
            2
        ],
        [
            64,
            240,
            3
        ],
        [
            240,
            99999,
            4
        ]
    ]
},
  control: {
    "32": 32,
    "36": 36,
    "44": 44,
    "48": 48,
    "56": 56,
    "64": 64
},
} as const;

export type ThemeColors = typeof tokens.color.light;
export const lightColors: ThemeColors = tokens.color.light;
export const darkColors: ThemeColors = tokens.color.dark;
