/* GENERATED by tools/generate-tokens.mjs from tokens.json v1. DO NOT EDIT. */

export const tokens = {
  meta: { version: 1 },
  color: {
    light: {
    "bg": "#F6F7F7",
    "surface": "#FFFFFF",
    "surfaceSoft": "#FAFBFB",
    "surfaceSunken": "#EEF0F0",
    "border": "#E2E5E5",
    "borderStrong": "#C7CCCC",
    "borderField": "#8B9293",
    "text1": "#14191A",
    "text2": "#4A5456",
    "text3": "#6C7679",
    "textDisabled": "#A2A9A9",
    "accent": "#0C6A62",
    "accentHover": "#0A5A54",
    "accentPress": "#095049",
    "accentInk": "#FFFFFF",
    "accentSoft": "#0C6A621F",
    "attn": "#8A5A00",
    "attnSoft": "#8A5A0016",
    "ok": "#146B3A"
},
    dark: {
    "bg": "#0E1213",
    "surface": "#171C1D",
    "surfaceSoft": "#131819",
    "surfaceSunken": "#0A0E0F",
    "border": "#272E2F",
    "borderStrong": "#394142",
    "borderField": "#697374",
    "text1": "#E9EDED",
    "text2": "#A4AEAE",
    "text3": "#7B8586",
    "textDisabled": "#4E5758",
    "accent": "#35C9B6",
    "accentHover": "#4FD6C4",
    "accentPress": "#63DFCE",
    "accentInk": "#04120F",
    "accentSoft": "#35C9B62E",
    "attn": "#E0A63A",
    "attnSoft": "#E0A63A24",
    "ok": "#3FC97E"
},
  },
  call: {
    fill: {
      light: ["#C4241A","#A81810","#8A100A"],
      dark: ["#B9271B","#CB2F22","#D93726"],
    },
    ink: {
      light: "#FFFFFF",
      dark: "#FFFFFF",
    },
    edge: {
      light: "#6E0A06",
      dark: "#FF6B54",
    },
    slab: {
      light: "#FFFFFF",
      dark: "#FFFFFF",
    },
    thresholdsSec: [0,30,120],
  },
  gutter: {
    "app": 24,
    "appNarrow": 16,
    "phone": 16,
    "wall": 32,
    "landing": 24,
    "watch": 10
},
  space: {
    "0": 0,
    "2": 2,
    "4": 4,
    "8": 8,
    "12": 12,
    "16": 16,
    "20": 20,
    "24": 24,
    "32": 32,
    "40": 40,
    "48": 48,
    "64": 64,
    "80": 80,
    "112": 112
},
  radius: {
    "0": 0,
    "1": 4,
    "2": 8,
    "3": 12,
    "4": 16,
    "full": 999,
    "bands": [
        [
            0,
            32,
            1
        ],
        [
            32,
            64,
            2
        ],
        [
            64,
            240,
            3
        ],
        [
            240,
            99999,
            4
        ]
    ]
},
  control: {
    "32": 32,
    "36": 36,
    "44": 44,
    "48": 48,
    "56": 56,
    "64": 64
},
} as const;

export type ThemeColors = typeof tokens.color.light;
export const lightColors: ThemeColors = tokens.color.light;
export const darkColors: ThemeColors = tokens.color.dark;
