// GENERATED by tools/generate-tokens.mjs from tokens.json v1. DO NOT EDIT.
//
// Only cross-surface facts live here: values where the phone disagreeing with
// the ward watch would mean two people looking at the same patient and seeing
// different urgency. The phone's own palette is in theme/tokens.dart.

/// Seconds at which a waiting call moves to the next urgency step.
const List<int> kCallThresholdsSec = [0, 120, 600];

/// The tokens.json version these came from, so a mismatch is traceable.
const int kTokensVersion = 1;
